#!/bin/bash
sudo su -
#Install AWS CLI and Completer
apt-get -y install python-pip
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
sudo pip install awscli
complete -C aws_completer aws
apt-get update
#Install Wget
apt-get install wget
#Install Git
apt-get install git
Y
#Install Midnight Commander
apt-get install mc
Y
#Install Traceroute
apt-get install traceroute
#Install EC2 API Tools
wget http://s3.amazonaws.com/ec2-downloads/ec2-api-tools.zip
sudo mkdir /usr/local/ec2
sudo unzip ec2-api-tools.zip -d /usr/local/ec2
cd /usr/local/ec2
ls
#Change Java to 1.6
sudo update-alternatives --config java
#Select option for 1.6. 
java -version
